# Generated by Django 4.1.5 on 2023-01-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Age", models.IntegerField()),
                ("Address", models.CharField(max_length=300)),
                ("Grade", models.CharField(max_length=100)),
                ("Major", models.CharField(max_length=200)),
            ],
        ),
    ]
